### ISSUE TITLE
detectron2/_C.cpython-37m-x86_64-linux-gnu.so: undefined symbol: THPVariableClass

### ISSUE THREAD

**Issue by molyswu** [xingyizhou/CenterNet2#1]
Tried to " python ./projects/CenterNet2/demo.py --config-fi4le ./projects/CenterNet2/configs/CenterNet2_DLA-BiFPN-P5_640_24x_ST.yaml --input ~/Downloads/dataset/2014/ --opts MODEL.WEIGHTS ./model/CenterNet2_DLA-BiFPN-P5_640_24x_ST.pth"
** fvcore version of PathManager will be deprecated soon. **
** Please migrate to the version in iopath repo. **
https://github.com/facebookresearch/iopath

Traceback (most recent call last):
  File "./projects/CenterNet2/demo.py", line 11, in <module>
    from detectron2.data.detection_utils import read_image
  File "/home/user/anaconda3/lib/python3.7/site-packages/detectron2/data/__init__.py", line 4, in <module>
    from .build import (
  File "/home/user/anaconda3/lib/python3.7/site-packages/detectron2/data/build.py", line 12, in <module>
    from detectron2.structures import BoxMode
  File "/home/user/anaconda3/lib/python3.7/site-packages/detectron2/structures/__init__.py", line 6, in <module>
    from .keypoints import Keypoints, heatmaps_to_keypoints
  File "/home/user/anaconda3/lib/python3.7/site-packages/detectron2/structures/k

detectron2/_C.cpython-37m-x86_64-linux-gnu.so: undefined symbol: THPVariableClass

**Comment by xingyizhou** [comment]
Hi,
  This seems a detectron2 installation issue. Can you check [here](https://detectron2.readthedocs.io/en/latest/tutorials/install.html#common-installation-issues)?

**Comment by molyswu** [comment]
The above issues have been solved. There are the following issues:
detectron2/layers/wrappers.py", line 85, in forward
    x, self.weight, self.bias, self.stride, self.padding, self.dilation, self.groups

RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED
