### ISSUE TITLE
run demo.py error

### ISSUE THREAD

**Issue by EdwardVincentMa** [xingyizhou/CenterNet2#44]
I added config，and then run demo.py, there is a new error as bellow: (My torch version is '1.8.1+cu111', on ubuntu 20.4)

Config 'projects/CenterNet2/configs/CenterNet2_R50_1x.yaml' has no VERSION. Assuming it to be compatible with latest v2.
Traceback (most recent call last):
  File "projects/CenterNet2/demo/demo.py", line 83, in <module>
    demo = VisualizationDemo(cfg)
  File "/home/mayc1/PyProject/detectron2/projects/CenterNet2/demo/predictor.py", line 35, in __init__
    self.predictor = DefaultPredictor(cfg)
  File "/home/mayc1/PyProject/detectron2/detectron2/engine/defaults.py", line 283, in __init__
    self.model = build_model(self.cfg)
  File "/home/mayc1/PyProject/detectron2/detectron2/modeling/meta_arch/build.py", line 22, in build_model
    model = META_ARCH_REGISTRY.get(meta_arch)(cfg)
  File "/home/mayc1/PyProject/detectron2/detectron2/config/config.py", line 174, in wrapped
    explicit_args = _get_args_from_config(from_config_func, *args, **kwargs)
  File "/home/mayc1/PyProject/detectron2/detectron2/config/config.py", line 229, in _get_args_from_config
    ret = from_config_func(*args, **kwargs)
  File "/home/mayc1/PyProject/detectron2/detectron2/modeling/meta_arch/rcnn.py", line 72, in from_config
    backbone = build_backbone(cfg)
  File "/home/mayc1/PyProject/detectron2/detectron2/modeling/backbone/build.py", line 31, in build_backbone
    backbone = BACKBONE_REGISTRY.get(backbone_name)(cfg, input_shape)
  File "/home/mayc1/anaconda3/lib/python3.8/site-packages/fvcore/common/registry.py", line 71, in get
    raise KeyError(
KeyError: "No object named 'build_p67_resnet_fpn_backbone' found in 'BACKBONE' registry!"

**Comment by Muhammadadeelaltaf** [comment]
[01/24 17:00:31 detectron2]: Arguments: Namespace(confidence_threshold=0.3, config_file='projects/CenterNet2/configs/CenterNet2_R50_1x.yaml', input=['test_images'], opts=['MODEL.WEIGHTS', 'models/CenterNet2_R50_1x.pth'], output=None, video_input=None, webcam=False)
WARNING [01/24 17:00:31 d2.config.compat]: Config 'projects/CenterNet2/configs/CenterNet2_R50_1x.yaml' has no VERSION. Assuming it to be compatible with latest v2.
Traceback (most recent call last):
  File "projects/CenterNet2/demo.py", line 80, in <module>
    demo = VisualizationDemo(cfg)
  File "/media/adeel/583C119E3C117868/CenterNet2/CenterNet2-master/projects/CenterNet2/predictor.py", line 35, in __init__
    self.predictor = DefaultPredictor(cfg)
  File "/media/adeel/583C119E3C117868/CenterNet2/CenterNet2-master/detectron2/engine/defaults.py", line 288, in __init__
    checkpointer.load(cfg.MODEL.WEIGHTS)
  File "/media/adeel/583C119E3C117868/CenterNet2/CenterNet2-master/detectron2/checkpoint/detection_checkpoint.py", line 52, in load
    ret = super().load(path, *args, **kwargs)
  File "/home/adeel/yes/envs/centerpoint/lib/python3.6/site-packages/fvcore/common/checkpoint.py", line 153, in load
    assert os.path.isfile(path), "Checkpoint {} not found!".format(path)
AssertionError: Checkpoint models/CenterNet2_R50_1x.pth not found!

Can you please help me to solve this error?
