### ISSUE TITLE
"No object named 'build_p67_resnet_fpn_backbone' found in 'BACKBONE' registry!"

### ISSUE THREAD

**Issue by EdwardVincentMa** [xingyizhou/CenterNet2#45]
Hello ~ Thank you for answer my question ~

When run demo.py there is error as bellow:

Config 'projects/CenterNet2/configs/CenterNet2_R50_1x.yaml' has no VERSION. Assuming it to be compatible with latest v2.
Traceback (most recent call last):
  File "projects/CenterNet2/demo/demo.py", line 83, in <module>
    demo = VisualizationDemo(cfg)
  File "/home/mayc1/PyProject/detectron2/projects/CenterNet2/demo/predictor.py", line 35, in __init__
    self.predictor = DefaultPredictor(cfg)
  File "/home/mayc1/PyProject/detectron2/detectron2/engine/defaults.py", line 283, in __init__
    self.model = build_model(self.cfg)
  File "/home/mayc1/PyProject/detectron2/detectron2/modeling/meta_arch/build.py", line 22, in build_model
    model = META_ARCH_REGISTRY.get(meta_arch)(cfg)
  File "/home/mayc1/PyProject/detectron2/detectron2/config/config.py", line 174, in wrapped
    explicit_args = _get_args_from_config(from_config_func, *args, **kwargs)
  File "/home/mayc1/PyProject/detectron2/detectron2/config/config.py", line 229, in _get_args_from_config
    ret = from_config_func(*args, **kwargs)
  File "/home/mayc1/PyProject/detectron2/detectron2/modeling/meta_arch/rcnn.py", line 72, in from_config
    backbone = build_backbone(cfg)
  File "/home/mayc1/PyProject/detectron2/detectron2/modeling/backbone/build.py", line 31, in build_backbone
    backbone = BACKBONE_REGISTRY.get(backbone_name)(cfg, input_shape)
  File "/home/mayc1/anaconda3/lib/python3.8/site-packages/fvcore/common/registry.py", line 71, in get
    raise KeyError(
KeyError: "No object named 'build_p67_resnet_fpn_backbone' found in 'BACKBONE' registry!"

**Comment by ThelilinNB** [comment]
Hello, have you solved this problem
